baseURL: "/"
languageCode: "en-us"
title: "Miguel Angel Lillo"
theme: hugo-profile
relativeUrls: true

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

# Menus:
  # main:
    # - identifier: blog
    #   name: Blog
    #   title: Blog posts
    #   url: /blogs
    #   weight: 1
    # - identifier: gallery
    #   name: Gallery
    #   title: Blog posts
    #   url: /gallery
    #   weight: 2
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Miguel Profile"
  description: Personal cool site
  # staticPath: ""  # The path to serve the static files from
  favicon: "/fav.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether to add mathjax support on all pages. Alternatively, you can opt-in per page by adding `mathjax: true` in the frontmatter.
  mathjax: false

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    defaultTheme: "dark" # dark

  font:
    fontSize: 1.2rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # When using hex codes for colors, quotations must be used along with the # sign
  # color:
  #   textColor: "#343a40"
  #   secondaryTextColor: "#6c757d"
  #   textLinkColor: "#007bff"
  #   backgroundColor: "#eaedf0"
  #   secondaryBackgroundColor: "#64ffda1a"
  #   primaryColor: "#007bff"
  #   secondaryColor: "#f8f9fa"

  #   darkmode:
  #     textColor: "#e4e6eb"
  #     secondaryTextColor: "#b0b3b8"
  #     textLinkColor: "#ffffff"
  #     backgroundColor: "#18191a"
  #     secondaryBackgroundColor: "#212529"
  #     primaryColor: "#ffffff"
  #     secondaryColor: "#212529"

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "Miguel Angel Lillo" # Brand name for the brand | default is the title variable
    disableSearch: true
    # searchPlaceholder: "Search"
    stickyNavBar:
      enable : true
      showOnScrollUp : true
    enableSeparator: true
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: true
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hola, mi nombre es"
    title: "Miguel"
    subtitle: "Desarrollo aplicaciones y páginas web"
    content: "Me apasiona resolver problemas y crear soluciones que le hagan más fácil la vida a las personas. Soy capaz de investigar y aprender lo que sea necesario para llegar a una solución viable. Disfruto el camino."
    image: /images/cover.png
    bottomImage:
      enable: true
    # roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "Currículum"
      url: "/cv_miguel_lillo.pdf"
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/miguel-saiph
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/miguel-angel-lillo-cabrera/
      customIcons:
        # - icon: /fav.png
        #   url: "https://example.com"

  # About
  about:
    enable: true
    title: "Sobre mí"
    image: "/images/profile.png"
    content: |-
      Soy un desarrollador de software con más de 5 años de experiencia en el desarrollo de aplicaciones web/móviles y páginas web.

      He trabajado principalmente en los rubros de la educación y el entretenimiento, con un foco puesto en la interactividad, bajo metodologías ágiles con equipos multidisciplinarios.

      Actualmente estoy buscando ampliar mi experiencia en otros rubros, desarrollando soluciones a problemas distintos a los que me he enfrentado anteriormente.
    skills:
      enable: true
      title: "Estas son algunas de las tecnologías con las que he trabajado:"
      items:
        - "HTML"
        - "CSS"
        - "JavaScript"
        - "TypeScript"
        - "C#"
        - "React"
        - "Node"
        - "Express"

  # Experience
  experience:
    enable: true
    title: "Experiencia Profesional"
    items:
      - job: "Desarrollador de Software"
        company: "Cangrejo Ideas"
        companyUrl: "https://cangrejoideas.com/"
        date: "Dic 2021 - Mar 2024"
        info:
          enable: false
        featuredLink:
          enable: true
          name: "Portafolio"
          url: "https://vimur.artstation.com/albums/11034782"
        content: | 
          Estuve a cargo de desarrollar videojuegos web/mobile para Cartoon Network USA/UK
          - Participé en más de 12 proyectos y lideré 7 de estos, participando en el modelado, prototipado, implementación, localización y entrega final.
          - Escribí documentación (a veces por iniciativa propia) de tareas repetitivas para mejorar los tiempos de desarrollo y QA. También realicé investigación de nuevas tecnologías para futuros proyectos.
          - Tecnologías más utilizadas:
            - TypeScript
            - JavaScript
            - Node
            - Gitlab

      - job: "Desarrollador Front End"
        company: "Adaptativamente"
        companyUrl: "https://www.linkedin.com/company/adaptativamente/"
        date: "Oct 2019 - May 2021"
        featuredLink:
          enable: false
          url: "https://example.com"
        info:
          enable: false
          content: I worked as a software developer for more than one year in Amazon.
        content: |
          Trabajé como desarrollador en una plataforma de enseñanza de matemáticas, en conjunto con profesores, diseñadores gráficos y programadores.
          - Desarrollé contenido interactivo para enseñar matemáticas de una manera entretenida. Estuve a cargo tanto del diseño como de la implementación.
          - Tecnologías más utilizadas:
            - JavaScript
            - CSS
            - Node
            - Jira

      - job: "Técnico de Desarrollo y Soporte Informático"
        company: "Cumbre Group"
        companyUrl: "https://www.linkedin.com/company/cumbre-group/"
        date: "Abr 2018 - Oct 2019"
        info:
          enable: false
        featuredLink:
          enable: true
          name: "Web a la que di más soporte"
          url: "https://www.transbankdevelopers.cl/"
        content: |
          Estuve encargado de brindar soporte y desarrollar mejoras a plataformas webs.
          - Además de mi trabajo como analista, desarrollé bases de datos y creé APIs Rest. 
          - Realicé integraciones de pasarelas de pago en webs de e-commerce.
          - Tecnologías más utilizadas:
            - JavaScript
            - PHP
            - React
            - Express

  # Education
  education:
    enable: false
    # title: "Custom Name"
    index: false
    items:
      - title: "Master of Business Administration"
        school:
          name: "University of California, Berkeley"
          url: "https://example.org"
        date: "2013 - 2015"
        GPA: "3.8 out of 5.0"
        content: |-
          Extracurricular Activities
            - Lorem ipsum dolor sit amet consectetur adipisicing elit.
            - Tempora esse, eaque delectus nulla quo doloribus itaque expedita alias natus optio totam maxime nihil excepturi velit a animi laborum hic similique.
      - title: "Bachelor of Science in Computer Science"
        school:
          name: "Massachusetts Institute of Technology"
          url: "https://example.org"
        date: "2009 - 2013"
        GPA: "3.9 out of 5.0"
        content: |-
          I Publiced two papers in the ACM SIGCHI Conference on Artificial Intelligence.
          - [Fast and Accurate Object Detection with a Single Convolutional Neural Network](https://example.com)
          - Face mask detection using a single convolutional neural network.

          Extracurricular Activities
            - Lorem ipsum dolor sit amet consectetur adipisicing elit.
            - Tempora esse, eaque delectus nulla quo doloribus itaque expedita alias natus optio totam maxime nihil excepturi velit a animi laborum hic similique.
        featuredLink:
          enable: true
          name: "My academic record"
          url: "https://example.com"
      - title: "High School"
        school:
          name: "Thomas Jefferson High School for Science and Technology."
          url: "https://example.org"
        GPA: "4.2 out of 5.0"
        featuredLink:
          enable: true
          url: "https://example.com"

  # Achievements
  achievements:
    enable: true
    title: "Hobbies"
    items:
      - title: Juegos de mesa
        content: Cuando no estoy resolviendo puzzles en el computador, estoy resolviendo puzzles en un tablero.
        # url: https://example.com
        image: /images/hobbies/bg.png
      - title: Observación de aves
        content: | 
          De vez en cuando voy a jornadas de observación de aves en Santiago o alrededores. 
          En el día a día siempre estoy atento a las aves que aparecen por el camino.
        image: /images/hobbies/bw.jpg
      - title: Kendo
        content: Practico este arte marcial que me permite ejercitar la atención, determinación, precisión y disciplina.
        image: /images/hobbies/kendo.jpg

  # projects
  projects:
    enable: true
    title: "Proyectos personales"
    items:
      - title: Harmonies Solo Companion
        content: Aplicación web y nativa (Android) para guardar progreso en el modo solitario del juego de mesa Harmonies.
        image: /images/projects/harmonies.png
        featured:
          name: Demo
          link: https://miguel-saiph.github.io/harmonies-solo-companion/
        badges:
          - "TypeScript"
          - "React Native"
          - "Expo"
        links:
          - icon: fab fa-github
            url: https://github.com/miguel-saiph/harmonies-solo-companion

      - title: Búsqueda de imágenes con Next.js
        content: Aplicación web para buscar imágenes usando la API Unsplash.
        image: /images/projects/image-search.png
        featured:
          name: Demo
          link: https://klog-test-pink.vercel.app/
        badges:
          - "React"
          - "Next"
          - "JavaScript"
        links:
          - icon: fab fa-github
            url: https://github.com/miguel-saiph/next.js-image-search

      - title: Cuphead Custom Companion (WIP)
        content: Aplicación compañera para el juego de mesa Cuphead Fast Rolling Dice. Es una mejora de la aplicación oficial presente en la PlayStore.
        image: /images/projects/cuphead.jpg
        badges:
          - "TypeScript"
          - "Cocos Creator"
          - "WebGL"
        links:
          - icon: fab fa-github
            url: https://github.com/miguel-saiph/cuphead-custom-companion

  #Contact
  contact:
    enable: true
    title: "Contacto"
    content: Si tienes alguna pregunta o sólo quieres ponerte en contacto, no dudes en contactarme.
    btnName: Mail me
    btnLink: mailto:miguelc12vm@gmail.com
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"
    #   messageRows: 5

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: true
      disableFeaturedImage: false
    socialNetworks:
      github: https://github.com/miguel-saiph
      linkedin: https://www.linkedin.com/in/miguel-angel-lillo-cabrera/
      # twitter: https://twitter.com
      # instagram: https://instagram.com
      # facebook: https://facebook.com

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    socialShare: true
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true
    tags:
      openInNewTab: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>